services:
  database:
    image: postgres:latest
    container_name: database
    env_file:
      - ./.env
    networks:
      - hyper-network
    volumes:
      - /tmp/db-data:/var/lib/postgresql/data
    restart: on-failure

  migration:
    image: python:3.12-slim
    container_name: migration
    env_file:
      - ./.env
    networks:
      - hyper-network
    volumes:
      - ./services/migration-service:/tmp/db
    depends_on:
      - database
    command: ["sh", "-c", "/tmp/db/init.sh"]
    restart: "no"

  data-service:
    build: ./services/data-service
    image: data-service
    container_name: data-service
    env_file:
      - ./.env
    volumes:
      - ./services/data-service:/app
      - ./grpc:/grpc
    depends_on:
      - migration
    networks:
      - hyper-network
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - /tmp/redis-data:/data
    networks:
      - hyper-network
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - hyper-network
    ports:
      - 80:80
    depends_on:
      - auth-service
      - user-service
      - stream-service
    restart: always
  
  auth-service:
    build: ./services/auth-service
    image: auth-service
    container_name: auth-service
    volumes:
      - ./services/auth-service:/app
      - ./grpc:/grpc
    env_file:
      - ./.env
    networks:
      - hyper-network
    depends_on:
      - migration
    restart: on-failure

  authorization-service:
    build: ./services/authorization-service
    image: authorization-service
    container_name: authorization-service
    volumes:
      - ./services/authorization-service:/app
      - ./grpc:/grpc
    env_file:
      - ./.env
    networks:
      - hyper-network
    restart: on-failure

  user-service:
    build: ./services/user-service
    image: user-service
    container_name: user-service
    volumes:
      - ./services/user-service:/app
      - ./grpc:/grpc
    env_file:
      - ./.env
    networks:
      - hyper-network
    depends_on:
      - migration
    restart: on-failure

  stream-service:
    build: ./services/stream-service
    image: stream-service
    container_name: stream-service
    volumes:
      - ./services/stream-service:/app
      - /app/node_modules
      - ./grpc:/grpc
      - ~/goinfre/hypertube:/downloads
    env_file:
      - ./.env
    networks:
      - hyper-network
    restart: on-failure

  cron-service:
    build: ./services/cron-service
    image: cron-service
    container_name: cron-service
    volumes:
      - ./services/cron-service:/app
      - ./grpc:/grpc
      - ~/goinfre/hypertube:/downloads
      - /app/node_modules
    env_file:
      - ./.env
    networks:
      - hyper-network
    depends_on:
      - database
    restart: on-failure

networks:
  hyper-network:
    driver: bridge
    name: hyper-network
