BEGIN;

INSERT INTO migrations (version, description) VALUES ('0003', 'added movies table');

CREATE TABLE IF NOT EXISTS movies (
    id VARCHAR(255) UNIQUE NOT NULL PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    downloaded BOOLEAN NOT NULL DEFAULT TRUE,
);

CREATE TABLE IF NOT EXISTS comments (
    id VARCHAR(255) UNIQUE NOT NULL PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    comment TEXT,
    FOREIGN KEY (movie_id) REFERENCES movies(id) ON DELETE CASCADE
);

COMMIT;